// Nyay AI - Shared Utilities
// Audit Logging, Session Management, Hash Verification

// ============================================
// SESSION MANAGEMENT
// ============================================

function getSession() {
    const sessionData = localStorage.getItem('nyai_user_session');
    return sessionData ? JSON.parse(sessionData) : null;
}

function saveSession(session) {
    localStorage.setItem('nyai_user_session', JSON.stringify(session));
}

function clearSession() {
    localStorage.removeItem('nyai_user_session');
}

function validateSession(requiredRole) {
    const session = getSession();
    if (!session) {
        alert('Session expired. Please login again.');
        window.location.href = 'index.html';
        return null;
    }
    
    if (requiredRole && session.role !== requiredRole) {
        alert('Unauthorized access. Redirecting to login.');
        window.location.href = 'index.html';
        return null;
    }
    
    return session;
}

// ============================================
// FORENSIC AUDIT LOGGING
// ============================================

function createForensicLog(roleId, action, details) {
    // Format: 2026-05-27_[RoleID]_[Action].md
    const date = new Date().toISOString().split('T')[0];
    const timestamp = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
    
    const logEntry = {
        filename: `${date}_${roleId}_${action}.md`,
        timestamp: new Date().toISOString(),
        content: `# Forensic Custody Log Entry

**Date:** ${timestamp}
**Role ID:** ${roleId}
**Action:** ${action}
**Session ID:** ${details.sessionId || 'N/A'}

## Details
\`\`\`json
${JSON.stringify(details, null, 2)}
\`\`\`

## Audit Trail
This action has been logged in the immutable forensic custody chain.
All timestamps are in IST (Indian Standard Time).

---
*Generated by Nyay AI - Digital Forensic Chain Ledger*
`
    };

    // Store log in localStorage (in production, this would be sent to backend)
    const logs = JSON.parse(localStorage.getItem('nyai_forensic_logs') || '[]');
    logs.push(logEntry);
    localStorage.setItem('nyai_forensic_logs', JSON.stringify(logs));
    
    console.log(`📝 Forensic log created: ${logEntry.filename}`);
    return logEntry;
}

function logAction(action, details) {
    const session = getSession();
    if (!session) return;
    
    createForensicLog(session.credentialId, action, {
        ...details,
        role: session.role,
        userName: session.name,
        sessionId: session.sessionId,
        timestamp: new Date().toISOString()
    });
}

// ============================================
// CRYPTOGRAPHIC HASH FUNCTIONS
// ============================================

async function generateSHA256(data) {
    const encoder = new TextEncoder();
    const dataBuffer = encoder.encode(data);
    const hashBuffer = await crypto.subtle.digest('SHA-256', dataBuffer);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

async function verifyPhotoHash(originalHash, photoBase64) {
    const newHash = await generateSHA256(photoBase64);
    return {
        match: originalHash === newHash,
        originalHash: originalHash,
        newHash: newHash
    };
}

// ============================================
// EVIDENCE ID GENERATION
// ============================================

function generateEvidenceId(type = 'CRIME') {
    const year = new Date().getFullYear();
    const random = Math.floor(Math.random() * 999999).toString().padStart(6, '0');
    
    if (type === 'MEDICAL') {
        return `MLC-${year}-${random}`;
    }
    return `EV-${year}-${random}`;
}

// ============================================
// EVIDENCE STORAGE
// ============================================

function saveEvidence(evidence) {
    // Get existing evidence lists
    let evidenceList = JSON.parse(localStorage.getItem('nyai_evidence_list') || '[]');
    
    // Add to appropriate list based on type
    if (evidence.type === 'MEDICAL_EVIDENCE') {
        let medicalList = JSON.parse(localStorage.getItem('nyai_medical_evidence_list') || '[]');
        medicalList.push(evidence.id);
        localStorage.setItem('nyai_medical_evidence_list', JSON.stringify(medicalList));
    } else {
        let crimeList = JSON.parse(localStorage.getItem('nyai_crime_evidence_list') || '[]');
        crimeList.push(evidence.id);
        localStorage.setItem('nyai_crime_evidence_list', JSON.stringify(crimeList));
    }
    
    evidenceList.push(evidence.id);
    localStorage.setItem('nyai_evidence_list', JSON.stringify(evidenceList));

    // Save individual evidence
    localStorage.setItem(`nyai_evidence_${evidence.id}`, JSON.stringify(evidence));

    // Initialize empty custody chain
    localStorage.setItem(`nyai_custody_${evidence.id}`, JSON.stringify([]));
    
    // Log the action
    logAction('EVIDENCE_REGISTRATION', {
        evidenceId: evidence.id,
        type: evidence.type,
        caseNumber: evidence.caseNumber,
        category: evidence.category
    });
}

function getEvidence(evidenceId) {
    const evidenceData = localStorage.getItem(`nyai_evidence_${evidenceId}`);
    return evidenceData ? JSON.parse(evidenceData) : null;
}

function updateEvidence(evidenceId, updates) {
    const evidence = getEvidence(evidenceId);
    if (!evidence) return null;
    
    const updatedEvidence = { ...evidence, ...updates };
    localStorage.setItem(`nyai_evidence_${evidenceId}`, JSON.stringify(updatedEvidence));
    
    return updatedEvidence;
}

// ============================================
// LAB FINDINGS MANAGEMENT
// ============================================

function addLabFinding(evidenceId, finding) {
    const findings = JSON.parse(localStorage.getItem(`nyai_lab_findings_${evidenceId}`) || '[]');
    
    const newFinding = {
        id: `FIND-${Date.now()}`,
        timestamp: new Date().toISOString(),
        ...finding
    };
    
    findings.push(newFinding);
    localStorage.setItem(`nyai_lab_findings_${evidenceId}`, JSON.stringify(findings));
    
    // Log the action
    logAction('LAB_FINDING_ADDED', {
        evidenceId: evidenceId,
        findingId: newFinding.id,
        findingType: finding.type
    });
    
    return newFinding;
}

function getLabFindings(evidenceId) {
    return JSON.parse(localStorage.getItem(`nyai_lab_findings_${evidenceId}`) || '[]');
}

// ============================================
// TAMPER ALERT MANAGEMENT
// ============================================

function createTamperAlert(evidenceId, details) {
    const alerts = JSON.parse(localStorage.getItem('nyai_tamper_alerts') || '[]');
    
    const alert = {
        id: `ALERT-${Date.now()}`,
        evidenceId: evidenceId,
        timestamp: new Date().toISOString(),
        severity: 'CRITICAL',
        ...details
    };
    
    alerts.push(alert);
    localStorage.setItem('nyai_tamper_alerts', JSON.stringify(alerts));
    
    // Log the critical event
    logAction('TAMPER_DETECTED', {
        evidenceId: evidenceId,
        alertId: alert.id,
        details: details
    });
    
    return alert;
}

function getTamperAlerts() {
    return JSON.parse(localStorage.getItem('nyai_tamper_alerts') || '[]');
}

// ============================================
// PERMISSION CHECKING
// ============================================

function checkPermission(action) {
    const session = getSession();
    if (!session || !session.permissions) return false;
    
    const permissionMap = {
        'register_evidence': 'canRegisterEvidence',
        'register_crime': 'canRegisterCrimeScene',
        'register_medical': 'canRegisterMedical',
        'transfer_custody': 'canTransferCustody',
        'verify_integrity': 'canVerifyIntegrity',
        'generate_report': 'canGenerateReport',
        'add_lab_findings': 'canAddLabFindings'
    };
    
    const permissionKey = permissionMap[action];
    return permissionKey ? session.permissions[permissionKey] === true : false;
}

function blockUnauthorizedAction(actionName) {
    const session = getSession();
    const roleName = session ? session.role.replace(/_/g, ' ') : 'Unknown';
    
    alert(`🚫 ACCESS DENIED\n\nRole: ${roleName}\nAction: ${actionName}\n\nYou do not have permission to perform this action.`);
    
    // Log unauthorized attempt
    logAction('UNAUTHORIZED_ATTEMPT', {
        attemptedAction: actionName,
        denied: true
    });
}

// ============================================
// DOM ISOLATION (SECURITY)
// ============================================

function unmountAllDashboards() {
    const dashboardIds = [
        'officer-dashboard',
        'medical-dashboard',
        'lab-dashboard',
        'judge-dashboard'
    ];
    
    dashboardIds.forEach(id => {
        const element = document.getElementById(id);
        if (element) {
            element.remove();
        }
    });
}

// ============================================
// UTILITY FUNCTIONS
// ============================================

function formatTimestamp(isoString) {
    return new Date(isoString).toLocaleString('en-IN', { 
        timeZone: 'Asia/Kolkata',
        dateStyle: 'medium',
        timeStyle: 'short'
    });
}

function generateSessionId() {
    return 'session_' + Date.now() + '_' + Math.random().toString(36).substr(2, 9);
}

function downloadQRCode(qrCanvas, evidenceId) {
    if (qrCanvas) {
        const link = document.createElement('a');
        link.download = `evidence-qr-${evidenceId}.png`;
        link.href = qrCanvas.toDataURL();
        link.click();
    }
}

// ============================================
// EXPORT FOR BROWSER USAGE
// ============================================

// Make functions available globally
window.NyayAI = {
    // Session
    getSession,
    saveSession,
    clearSession,
    validateSession,
    
    // Logging
    createForensicLog,
    logAction,
    
    // Crypto
    generateSHA256,
    verifyPhotoHash,
    
    // Evidence
    generateEvidenceId,
    saveEvidence,
    getEvidence,
    updateEvidence,
    
    // Lab
    addLabFinding,
    getLabFindings,
    
    // Tamper
    createTamperAlert,
    getTamperAlerts,
    
    // Permissions
    checkPermission,
    blockUnauthorizedAction,
    
    // Security
    unmountAllDashboards,
    
    // Utils
    formatTimestamp,
    generateSessionId,
    downloadQRCode
};

// Made with Bob
